/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_6 (
    input clk,
    input rst,
    input [511:0] r,
    input [511:0] g,
    input [511:0] b,
    output reg red2,
    output reg green2,
    output reg blue2,
    output reg red1,
    output reg green1,
    output reg blue1,
    output reg oe,
    output reg lat,
    output reg clock,
    output reg a_1,
    output reg c_1,
    output reg b_1
  );
  
  
  
  reg [10:0] M_columnClk_d, M_columnClk_q = 1'h0;
  
  reg [3:0] test;
  
  reg [3:0] test1;
  
  always @* begin
    M_columnClk_d = M_columnClk_q;
    
    a_1 = M_columnClk_q[8+0-:1];
    b_1 = M_columnClk_q[9+0-:1];
    c_1 = M_columnClk_q[10+0-:1];
    if (M_columnClk_q[1+6-:7] == 7'h7f) begin
      lat = 1'h1;
    end else begin
      lat = 1'h0;
    end
    if (M_columnClk_q[0+7-:8] > 8'h80) begin
      oe = 1'h0;
    end else begin
      oe = 1'h1;
    end
    test1[0+0-:1] = M_columnClk_q[8+0-:1];
    test1[1+0-:1] = M_columnClk_q[9+0-:1];
    test1[2+0-:1] = M_columnClk_q[10+0-:1];
    test1[3+0-:1] = 1'h0;
    test[0+0-:1] = M_columnClk_q[8+0-:1];
    test[1+0-:1] = M_columnClk_q[9+0-:1];
    test[2+0-:1] = M_columnClk_q[10+0-:1];
    test[3+0-:1] = 1'h1;
    red1 = r[(test1)*32+(M_columnClk_q[1+4-:5])*1+0-:1];
    green1 = g[(test1)*32+(M_columnClk_q[1+4-:5])*1+0-:1];
    blue1 = b[(test1)*32+(M_columnClk_q[1+4-:5])*1+0-:1];
    red2 = r[(test)*32+(M_columnClk_q[1+4-:5])*1+0-:1];
    green2 = g[(test)*32+(M_columnClk_q[1+4-:5])*1+0-:1];
    blue2 = b[(test)*32+(M_columnClk_q[1+4-:5])*1+0-:1];
    clock = M_columnClk_q[0+0-:1];
    M_columnClk_d = M_columnClk_q + 1'h1;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_columnClk_q <= 1'h0;
    end else begin
      M_columnClk_q <= M_columnClk_d;
    end
  end
  
endmodule
