/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module initialize_7 (
    input clk,
    input rst,
    input [2:0] stage,
    output reg [63:0] array,
    output reg score,
    output reg out
  );
  
  
  
  reg [63:0] number;
  
  always @* begin
    out = 1'h0;
    score = 1'h0;
    
    case (stage)
      1'h1: begin
        number[0+3-:4] = 4'h0;
        number[4+3-:4] = 4'h3;
        number[8+3-:4] = 4'h2;
        number[12+3-:4] = 4'h1;
        number[16+3-:4] = 4'h4;
        number[20+3-:4] = 4'h5;
        number[24+3-:4] = 4'h6;
        number[28+3-:4] = 4'h7;
        number[32+3-:4] = 4'h8;
        number[36+3-:4] = 4'h9;
        number[40+3-:4] = 4'ha;
        number[44+3-:4] = 4'hb;
        number[48+3-:4] = 4'hc;
        number[52+3-:4] = 4'hd;
        number[56+3-:4] = 4'he;
        number[60+3-:4] = 4'hf;
      end
      2'h2: begin
        number[0+3-:4] = 4'h0;
        number[4+3-:4] = 4'h1;
        number[8+3-:4] = 4'h2;
        number[12+3-:4] = 4'h3;
        number[16+3-:4] = 4'h4;
        number[20+3-:4] = 4'h5;
        number[24+3-:4] = 4'h6;
        number[28+3-:4] = 4'h7;
        number[32+3-:4] = 4'h9;
        number[36+3-:4] = 4'h8;
        number[40+3-:4] = 4'ha;
        number[44+3-:4] = 4'hb;
        number[48+3-:4] = 4'hc;
        number[52+3-:4] = 4'hd;
        number[56+3-:4] = 4'he;
        number[60+3-:4] = 4'hf;
      end
      2'h3: begin
        number[0+3-:4] = 4'h0;
        number[4+3-:4] = 4'h1;
        number[8+3-:4] = 4'h2;
        number[12+3-:4] = 4'h3;
        number[16+3-:4] = 4'h4;
        number[20+3-:4] = 4'h5;
        number[24+3-:4] = 4'h6;
        number[28+3-:4] = 4'h8;
        number[32+3-:4] = 4'h7;
        number[36+3-:4] = 4'h9;
        number[40+3-:4] = 4'ha;
        number[44+3-:4] = 4'hb;
        number[48+3-:4] = 4'hc;
        number[52+3-:4] = 4'hd;
        number[56+3-:4] = 4'he;
        number[60+3-:4] = 4'hf;
      end
      3'h4: begin
        number[0+3-:4] = 4'h0;
        number[4+3-:4] = 4'h1;
        number[8+3-:4] = 4'h2;
        number[12+3-:4] = 4'h3;
        number[16+3-:4] = 4'h4;
        number[20+3-:4] = 4'h5;
        number[24+3-:4] = 4'h6;
        number[28+3-:4] = 4'h7;
        number[32+3-:4] = 4'h8;
        number[36+3-:4] = 4'h9;
        number[40+3-:4] = 4'ha;
        number[44+3-:4] = 4'hb;
        number[48+3-:4] = 4'hc;
        number[52+3-:4] = 4'hd;
        number[56+3-:4] = 4'hf;
        number[60+3-:4] = 4'he;
      end
      3'h5: begin
        number[0+3-:4] = 4'h0;
        number[4+3-:4] = 4'h1;
        number[8+3-:4] = 4'h2;
        number[12+3-:4] = 4'h3;
        number[16+3-:4] = 4'h4;
        number[20+3-:4] = 4'h5;
        number[24+3-:4] = 4'h6;
        number[28+3-:4] = 4'h7;
        number[32+3-:4] = 4'hc;
        number[36+3-:4] = 4'hd;
        number[40+3-:4] = 4'he;
        number[44+3-:4] = 4'hf;
        number[48+3-:4] = 4'h8;
        number[52+3-:4] = 4'h9;
        number[56+3-:4] = 4'ha;
        number[60+3-:4] = 4'hb;
      end
      default: begin
        number[0+3-:4] = 4'h0;
        number[4+3-:4] = 4'h1;
        number[8+3-:4] = 4'h2;
        number[12+3-:4] = 4'h3;
        number[16+3-:4] = 4'h4;
        number[20+3-:4] = 4'h5;
        number[24+3-:4] = 4'h6;
        number[28+3-:4] = 4'h7;
        number[32+3-:4] = 4'h8;
        number[36+3-:4] = 4'h9;
        number[40+3-:4] = 4'ha;
        number[44+3-:4] = 4'hb;
        number[48+3-:4] = 4'hc;
        number[52+3-:4] = 4'hd;
        number[56+3-:4] = 4'he;
        number[60+3-:4] = 4'hf;
      end
    endcase
    array = number;
  end
endmodule
