/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module starting_screen_1 (
    output reg [511:0] place
  );
  
  
  
  always @* begin
    place[64+2+0-:1] = 1'h1;
    place[64+3+0-:1] = 1'h1;
    place[64+4+0-:1] = 1'h1;
    place[64+5+0-:1] = 1'h1;
    place[96+6+0-:1] = 1'h1;
    place[96+2+0-:1] = 1'h1;
    place[128+2+0-:1] = 1'h1;
    place[128+7+0-:1] = 1'h1;
    place[160+6+0-:1] = 1'h1;
    place[160+2+0-:1] = 1'h1;
    place[192+2+0-:1] = 1'h1;
    place[192+3+0-:1] = 1'h1;
    place[192+4+0-:1] = 1'h1;
    place[192+5+0-:1] = 1'h1;
    place[480+2+0-:1] = 1'h1;
    place[480+6+0-:1] = 1'h1;
    place[256+2+0-:1] = 1'h1;
    place[256+7+0-:1] = 1'h1;
    place[288+2+0-:1] = 1'h1;
    place[288+6+0-:1] = 1'h1;
    place[320+2+0-:1] = 1'h1;
    place[320+3+0-:1] = 1'h1;
    place[320+4+0-:1] = 1'h1;
    place[320+5+0-:1] = 1'h1;
    place[192+9+0-:1] = 1'h1;
    place[192+10+0-:1] = 1'h1;
    place[192+11+0-:1] = 1'h1;
    place[192+12+0-:1] = 1'h1;
    place[480+9+0-:1] = 1'h1;
    place[256+9+0-:1] = 1'h1;
    place[256+10+0-:1] = 1'h1;
    place[256+11+0-:1] = 1'h1;
    place[256+12+0-:1] = 1'h1;
    place[288+9+0-:1] = 1'h1;
    place[320+9+0-:1] = 1'h1;
    place[320+10+0-:1] = 1'h1;
    place[320+11+0-:1] = 1'h1;
    place[320+12+0-:1] = 1'h1;
    place[192+15+0-:1] = 1'h1;
    place[192+16+0-:1] = 1'h1;
    place[192+17+0-:1] = 1'h1;
    place[480+14+0-:1] = 1'h1;
    place[256+14+0-:1] = 1'h1;
    place[256+16+0-:1] = 1'h1;
    place[256+17+0-:1] = 1'h1;
    place[288+14+0-:1] = 1'h1;
    place[288+17+0-:1] = 1'h1;
    place[320+15+0-:1] = 1'h1;
    place[320+16+0-:1] = 1'h1;
    place[192+19+0-:1] = 1'h1;
    place[192+20+0-:1] = 1'h1;
    place[192+21+0-:1] = 1'h1;
    place[192+22+0-:1] = 1'h1;
    place[192+23+0-:1] = 1'h1;
    place[480+21+0-:1] = 1'h1;
    place[256+21+0-:1] = 1'h1;
    place[288+21+0-:1] = 1'h1;
    place[320+19+0-:1] = 1'h1;
    place[320+20+0-:1] = 1'h1;
    place[320+21+0-:1] = 1'h1;
    place[320+22+0-:1] = 1'h1;
    place[320+23+0-:1] = 1'h1;
    place[192+25+0-:1] = 1'h1;
    place[192+29+0-:1] = 1'h1;
    place[480+25+0-:1] = 1'h1;
    place[480+26+0-:1] = 1'h1;
    place[480+29+0-:1] = 1'h1;
    place[256+25+0-:1] = 1'h1;
    place[256+27+0-:1] = 1'h1;
    place[256+29+0-:1] = 1'h1;
    place[288+25+0-:1] = 1'h1;
    place[288+28+0-:1] = 1'h1;
    place[288+29+0-:1] = 1'h1;
    place[320+25+0-:1] = 1'h1;
    place[320+29+0-:1] = 1'h1;
  end
endmodule
