/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module switcher_8 (
    input clk,
    input rst,
    input [3:0] location1,
    input [3:0] location2,
    input [63:0] numberArray,
    output reg [63:0] newNumberArray
  );
  
  
  
  always @* begin
    newNumberArray = numberArray;
    newNumberArray[(location1)*4+3-:4] = numberArray[(location2)*4+3-:4];
    newNumberArray[(location2)*4+3-:4] = numberArray[(location1)*4+3-:4];
  end
endmodule
